name: Deploy Backend

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            cd ~/teacheron-backend

            echo "Pulling latest code..."
            git fetch origin
            git reset --hard origin/main

            echo "Installing dependencies..."
            npm install

            echo "Restarting PM2..."
            pm2 restart teacherpoint-api

            echo "Deployment completed!"